_target_: world_generators.dynamicrafter.DynamiCrafter
model_name: dynamicrafter_512_i2v
ckpt_path: thirdparty/DynamiCrafter/checkpoints/dynamicrafter_512_v1/model.ckpt
config: thirdparty/DynamiCrafter/configs/inference_512_v1.0.yaml
height: 320
width: 512
video_length: 50
frame_stride: 24
guidance_rescale: 0.7
timestep_spacing: uniform_trailing 
text_input: True
perframe_ae: True
generation_type: i2v

