_target_: world_generators.ltx_video.LTXVideo
model_name: ltx_video_i2v
generation_type: i2v
num_images_per_prompt: 1
image_cond_noise_scale: 0.15
height: 512
width: 768
num_frames: 121
frame_rate: 30
pipeline_config: thirdparty/LTX-Video/configs/ltxv-13b-0.9.7-dev.yaml
negative_prompt: "worst quality, inconsistent motion, blurry, jittery, distorted"
conditioning_start_frames: 0