_target_: world_generators.videocrafter.VideoCrafter
model_name: videocrafter2_t2v
ckpt_path: world_generators/checkpoints/videocrafter_t2v_512_v2.ckpt
config: thirdparty/VideoCrafter/configs/inference_t2v_512_v2.0.yaml
height: 320
width: 512
fps: 8
generation_type: t2v